[package]
name = "embedded-registers"
edition = "2021"
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
embedded-hal = "1.0.0-rc.1"
embedded-hal-async = "1.0.0-rc.1"
embedded-registers-derive = { version = "1.0.0", path = "../embedded-registers-derive", optional = true }

[features]
default = ["derive"]
derive = ["embedded-registers-derive"]
std = []
