[package]
name = "embedded-registers"
edition = "2021"
documentation = "https://docs.rs/embedded-registers"
version.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
embedded-hal = "1.0.0-rc.1"
embedded-hal-async = "1.0.0-rc.1"
embedded-registers-derive = { version = "0.9.2", path = "../embedded-registers-derive", optional = true }

[features]
default = ["derive"]
derive = ["embedded-registers-derive"]
std = []
