[package]
name = "embedded-registers"
edition = "2021"
authors.workspace = true
description.workspace = true
documentation.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
embedded-registers-derive = { path = "../embedded-registers-derive", optional = true }

[features]
default = ["derive"]
derive = ["embedded-registers-derive"]
std = []
