[workspace]
resolver = "2"
members = [
	"embedded-registers",
	"embedded-registers-derive",
]

[workspace.package]
version = "0.9.0"
authors = ["oddlama <oddlama@oddlama.org>"]
description = "Procedural macro for effortless definitions of registers in embedded device drivers"
documentation = "https://github.com/oddlama/embedded-registers"
homepage = "https://github.com/oddlama/embedded-registers"
repository = "https://github.com/oddlama/embedded-registers"
keywords = ["register", "registers", "bitfield", "derive", "sensor"]
categories = ["embedded", "no-std", "hardware-support", "embedded-hal"]
license = "MIT OR Apache-2.0"
